# Generated by Django 2.2.12 on 2021-07-01 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 7, 1, 19, 52, 27, 799808))),
                ('ip', models.GenericIPAddressField(default='', editable=False)),
                ('user_agent', models.CharField(default='', max_length=511)),
                ('content_length', models.IntegerField(default=0)),
                ('content_type', models.CharField(max_length=255, null=True)),
                ('host', models.URLField(null=True)),
                ('accept', models.CharField(max_length=255, null=True)),
                ('accept_language', models.CharField(max_length=255, null=True)),
                ('accept_encoding', models.CharField(max_length=255, null=True)),
                ('server_name', models.CharField(default='', max_length=255)),
                ('server_port', models.IntegerField(default=0)),
                ('referer', models.URLField(null=True)),
                ('method', models.CharField(default='POST', max_length=15)),
                ('query_string', models.CharField(max_length=255, null=True)),
                ('cookie', models.CharField(max_length=1023, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=400)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserPassMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=400)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
