# Generated by Django 2.2.12 on 2021-07-01 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 19, 53, 40, 155593)),
        ),
    ]
