# Generated by Django 3.2.4 on 2021-07-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_attempt_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
