# Generated by Django 3.2.4 on 2021-07-04 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_attempt_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='password',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 19, 49, 21, 876000)),
        ),
    ]
